apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fg2gnhuda-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fg2gnhuda-java-quarkus-gitops